name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
      - name: check
        with:
          java-version: 17
          distribution: zulu
        run: sh ./scripts/check-all
